// This file will be generated by Vercel with environment variables
// For local development, this will be ignored and .env will be used instead
if (typeof window !== 'undefined') {
    window.VERCEL_CONFIG = {
        GOOGLE_API_KEY: "%%GOOGLE_API_KEY%%"
    };
}
